### ISSUE TITLE
Improve User Todo List

### ISSUE THREAD

**Issue by vincentktieu-ucsb** [vincentktieu-ucsb/MakeTodo#13]
As a user, I want my todo list to be in order and not include todos that have a passed deadline or ones I've completed.

- [ ] doesn't render todos with passed deadline
- [ ] orders the todos
- [ ] doesn't render todos already completed
