### ISSUE TITLE
Users Todo Counts

### ISSUE THREAD

**Issue by vincentktieu-ucsb** [vincentktieu-ucsb/MakeTodo#5]
As a user, I want a space to see what progress I've made in my todos. 

I want both WEEKLY and ALL-TIME stats of how many todos I've completed.

--------- FRONTEND ---------
- [x] combine the user section to todolist so page is kept responsive
- [x] render completed todo count on weekly list
- [x] render completed todo count on total list

--------- BACKEND ---------
- [ ] get total number of todos completed
- [ ] get total number of todos failed
- [ ] get all the todos completed in the last week
